### ISSUE TITLE
工具栏配置在编辑器实例化后还能修改么？

### ISSUE THREAD

**Issue by cribug** [wangeditor-team/wangEditor-for-react#14]
在全屏模式和非全屏模式下需要显示不一样的工具栏，但是我看文档和源码都好像支持不了

原本想着监听状态是否全屏，做工具栏配置修改，但是好像在编辑器实例初始化后，工具栏配置就不允许修改了

![QQ20220803-0](https://user-images.githubusercontent.com/13611588/182561058-376aa84b-7b28-4687-8619-6af7236d97f6.png)

**Comment by wangfupeng1988** [comment]
> 编辑器实例初始化后，工具栏配置就不允许修改了

是的，目前不支持
