### ISSUE TITLE
Readonly无效的问题,我认为此处不应该Return；

### ISSUE THREAD

**Issue by zhangjindong** [wangeditor-team/wangEditor-for-react#7]
https://github.com/wangeditor-team/wangEditor-for-react/blob/59c5e7f9873c3a690e57cc36679b329e87fb2a55/src/components/Editor.tsx#L80

我认为此处不应该Return；会导致Readonly无效的问题；
如图：假如开始是只读状态；

![image](https://user-images.githubusercontent.com/5567162/165208775-9ff717f8-9bd0-486c-b1c6-dabd67b952c0.png)

**Comment by zhangjindong** [comment]
例如：两个编辑器，一个编辑，一个只读。
https://codesandbox.io/embed/brave-platform-cynjk4?fontsize=14&hidenavigation=1&theme=dark

**Comment by wangfupeng1988** [comment]
已经再这里记录了，在修改中了。
https://github.com/wangeditor-team/wangEditor/issues/4103
