### ISSUE TITLE
多个编辑器标题样式异常

### ISSUE THREAD

**Issue by shaw-Lee** [wangeditor-team/wangEditor-for-react#9]
![image](https://user-images.githubusercontent.com/78359360/169938898-7a9f4c8a-27e2-47d7-be54-da2f5bc90d93.png)

**Comment by wangfupeng1988** [comment]
单个编辑器，标题样式就没异常吗？

**Comment by shaw-Lee** [comment]
没有

**Comment by wangfupeng1988** [comment]
你用浏览器检查工具看看，是不是全局样式的污染？
